In [3]:
import os
import cv2 as cv
import numpy as np
import json

In [10]:
files_imgs = [os.path.join(DIR, 'images', f) for f in files_imgs]

In [11]:
with open (os.path.join(DIR,'dataset.json')) as f:
    keypoints_data = json.load(f)
    keypoints_data = keypoints_data['dataset']

In [14]:
path = []
cornerpoints = []
for i in range(0,len(keypoints_data)):
 
    data = keypoints_data[i]
    path.append(data['image_path'])
    corners = data['corner_keypoints']
    corners2 = list(map(lambda j : j[::-1] , corners))
    cornerpoints.append(corners2)
   
    keypoints_contents  = zip(path,cornerpoints)


In [21]:
path = list(map(lambda i : (i.split('/')[0]).split('.')[0] ,path))
path

['box0',
 'box1',
 'box2',
 'box3',
 'box4',
 'box5',
 'box6',
 'box7',
 'box8',
 'box9',
 'box10',
 'box11',
 'box12',
 'box13',
 'box14',
 'box15',
 'box16',
 'box17',
 'box18',
 'box19',
 'box20',
 'box21',
 'box22',
 'box23',
 'box24',
 'box25',
 'box26',
 'box27',
 'box28',
 'box29',
 'box30',
 'box31',
 'box32',
 'box33',
 'box34',
 'box35',
 'box36',
 'box37',
 'box38',
 'box39',
 'box40',
 'box41',
 'box42',
 'box43',
 'box44',
 'box45',
 'box46',
 'box47',
 'box48',
 'box49',
 'box50',
 'box51',
 'box52',
 'box53',
 'box54',
 'box55',
 'box56',
 'box57',
 'box58',
 'box59',
 'box60',
 'box61',
 'box62',
 'box63',
 'box64',
 'box65',
 'box66',
 'box67',
 'box68',
 'box69',
 'box70',
 'box71',
 'box72',
 'box73',
 'box74',
 'box75',
 'box76',
 'box77',
 'box78',
 'box79',
 'box80',
 'box81',
 'box82',
 'box83',
 'box84',
 'box85',
 'box86',
 'box87',
 'box88',
 'box89',
 'box90',
 'box91',
 'box92',
 'box93',
 'box94',
 'box95',
 'box96',
 'box97',
 'box98',
 'box99',
 'box100',

In [49]:
cornerpoints[0]

[[0.3520905375480652, 0.5514724254608154],
 [0.46924370527267456, 0.34643998742103577],
 [0.6479094624519348, 0.4485275447368622],
 [0.5307562947273254, 0.6535599827766418]]

In [50]:
data = keypoints_data[0]
a = data['corner_keypoints']
a

[[0.5514724254608154, 0.3520905375480652],
 [0.34643998742103577, 0.46924370527267456],
 [0.4485275447368622, 0.6479094624519348],
 [0.6535599827766418, 0.5307562947273254]]

In [51]:
pts = np.array(a, np.float32)

pts = np.multiply(pts,256)
pts 

array([[141.17694,  90.13518],
       [ 88.68864, 120.12639],
       [114.82305, 165.86482],
       [167.31136, 135.87361]], dtype=float32)

In [52]:
256-pts[0][1]

165.8648223876953

In [53]:
for i in range(0,len(pts)):
    pts[i][1] = 256-pts[i][1]

In [54]:
pts

array([[141.17694, 165.86482],
       [ 88.68864, 135.87361],
       [114.82305,  90.13518],
       [167.31136, 120.12639]], dtype=float32)

In [55]:
pts = pts.reshape((-1,1,2))
pts = pts.astype(int)
pts

array([[[141, 165]],

       [[ 88, 135]],

       [[114,  90]],

       [[167, 120]]])

SyntaxError: unexpected EOF while parsing (1193701652.py, line 1)

In [40]:
list(map(lambda j : j[::-1] , a))

[[0.5514724254608154, 0.3520905375480652],
 [0.46924370527267456, 0.34643998742103577],
 [0.6479094624519348, 0.4485275447368622],
 [0.5307562947273254, 0.6535599827766418]]

In [35]:
a = cornerpoints[0][0][::-1]

print(a)

[0.3520905375480652, 0.5514724254608154]


In [ ]:
x = np.random.randint(low=0, high=len(path))

img = cv.imread(os.path.join(DIR,path[x]))
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
#blank = np.zeros((200,200,3), dtype='uint8')
pts = np.array(256*cornerpoints[x], np.int32)
pts = pts.reshape((-1,1,2))
cv.polylines(img,[pts],True,(0,255,0),thickness=2)


cv.imshow('sample', img)

cv.waitKey(0)







In [ ]:
gray.shape()

In [5]:
a='skdfb\knsdjv'

In [6]:
a


'skdfb\\knsdjv'

In [7]:
a.split('\\')[1]

'knsdjv'